### ISSUE TITLE
Create Survey

### ISSUE THREAD

**Issue by semujju** [mwakaambrose/ug-poll#5]
Create survey questions dinamically, ie users define their own questions and attach multiple choice answers

- A survey should have a title

- Questions reference the title

- Multiple Choice answers reference the question

- We need to store responses from a set of respondents for the questions sent to them

**Comment by jorgie-o** [comment]
i kinder love this UI. @mwakaambrose u will need to run on JS
![screen shot 2018-06-20 at 11 06 18 am](https://user-images.githubusercontent.com/11919930/41645622-28c6fd80-747a-11e8-942e-8c52b9d9a5ac.png)
https://surveyjs.io/Overview/Library/

**Comment by semujju** [comment]
Looks nice @jorgie-o , tho i will let @mwakaambrose make a decision, he is the UI guy here.

**Comment by pirupius** [comment]
already completed #8 and #10
